tickers:
  - AAPL
  - GOOGL
  - MSFT
  - AMZN
  - META
  - NFLX
  - NVDA
  - AMD
  - AVGO
  - TSM
  - QCOM
  - PLTR
  - SNOW
  - TSLA
  - CRM
  - ORCL
  - DDOG
  - HUBS
  - INTU
  - TEAM
  - NOW
  - ADBE
  - CRWD
  - FTNT
  - CYBR
  - NET
  - SHOP
  - RY
  - TD
  - BMO
  - BNS
  - OTEX
  - LSPD
  - CSU
  - CNQ
  - ENB
  - SU
  - TRP
  - CNR
  - CP
  - COIN
  - HOOD
  - V
  - PYPL
  - MA
  - SLF
  - MFC
  - IFC
  - LLY